import type { Question } from "~/src/modules/Onboarding/types/OnboardingQuestion";

// TODO: think about whether questions should be here or on the backend
export const onboardingQuestions: Question[] = [
  {
    key: "name",
    label: "what is your name?",
    type: "text",
    required: true,
    // TODO: this should be two input boxes for first name and last name
  },
  {
    key: "date_of_birth",
    label: "what is your birth date?",
    type: "date",
    required: true,
  },
  {
    key: "based_in",
    label: "where are you based?",
    type: "text",
    required: true,
  },
  {
    key: "work_types",
    label: "what do you do?",
    type: "multi-choice",
    options: [
      "director",
      "filmmaker",
      "gaffer",
      "lighting technician",
      "drone operator",
      "editor",
      "colorist",
      "motion graphics artist",
      "vfx artist",
      "production designer",
      "scriptwriter / screenwriter",
      "set designer",
      "behind-the-scenes (bts) photographer",
      "behind-the-scenes (bts) videographer",
    ],
    required: true,
    // TODO: implement limit (3) for how many choices user can make here
  },
  {
    key: "project_types",
    label: "what types of projects do you usually work on?",
    type: "multi-choice",
    options: [
      "commercial video campaigns",
      "branded content",
      "fashion films",
      "music videos",
      "short films",
      "feature films",
      "product films / ads",
      "documentary",
      "social media video content",
      "event coverage / video",
      "green screen / vfx projects",
      "food & beverage cinematic ads",
      "behind-the-scenes (bts) documentation",
      "luxury & lifestyle videos",
      "studio shoots",
      "interviews & talking head videos",
      "cinematic storytelling",
      "action / sports cinematography",
      "automotive cinematography",
      "drone cinematography",
      "live performance filming",
      "360° / vr content",
      "slow-motion / high-speed cinematography",
    ],
    required: true,
  },
  {
    key: "socials",
    label: "where can we see your work?",
    type: "text", // TODO: should be social
    required: true,
  },
  {
    key: "additional_info",
    label: "is there anything else we should know?",
    type: "text",
    required: false,
  },
];
