import type { Question } from "~/src/modules/Onboarding/types/onboardingTypes";

// TODO: think about whether questions should be here or on the backend
export const onboardingQuestions: Question[] = [
  {
    key: "name_question",
    label: "what is your name?",
    required: true,
    fields: [
      {
        key: "fist_name",
        type: "text",
        label: "first name",
        required: true,
        placeholder: "name",
      },
      {
        key: "last_name",
        type: "text",
        label: "last name",
        required: true,
        placeholder: "name",
      },
    ],
  },
  {
    key: "date_of_birth_question",
    label: "what is your birth date?",
    required: true,
    fields: [
      {
        key: "date_of_birth",
        type: "date",
        label: "date of birth",
        required: true,
      },
    ],
  },
  {
    key: "based_in_question",
    label: "where are you based?",
    required: true,
    fields: [
      {
        key: "based_in",
        type: "text",
        label: "location",
        required: true,
        placeholder: "place",
      },
    ],
  },
  {
    key: "work_types_question",
    label: "what do you do?",
    description:
      "(choose up to three roles that best describe your work in video production)",
    required: true,
    fields: [
      {
        key: "work_types_search",
        type: "text",
        label: "search for your role or select from the list",
        icon: "/icons/search.svg",
        required: false,
        placeholder: "search",
      },
      {
        key: "work_types",
        type: "multi-choice",
        label: "",
        options: [
          "director",
          "filmmaker",
          "gaffer",
          "lighting technician",
          "drone operator",
          "editor",
          "colorist",
          "motion graphics artist",
          "vfx artist",
          "production designer",
          "scriptwriter / screenwriter",
          "set designer",
          "behind-the-scenes (bts) photographer",
          "behind-the-scenes (bts) videographer",
        ],
        minChoices: 1,
        maxChoices: 3,
      },
    ],
  },
  // {
  //   key: "project_types",
  //   label: "what types of projects do you usually work on?",
  //   type: "multi-choice",
  //   options: [
  //     "commercial video campaigns",
  //     "branded content",
  //     "fashion films",
  //     "music videos",
  //     "short films",
  //     "feature films",
  //     "product films / ads",
  //     "documentary",
  //     "social media video content",
  //     "event coverage / video",
  //     "green screen / vfx projects",
  //     "food & beverage cinematic ads",
  //     "behind-the-scenes (bts) documentation",
  //     "luxury & lifestyle videos",
  //     "studio shoots",
  //     "interviews & talking head videos",
  //     "cinematic storytelling",
  //     "action / sports cinematography",
  //     "automotive cinematography",
  //     "drone cinematography",
  //     "live performance filming",
  //     "360° / vr content",
  //     "slow-motion / high-speed cinematography",
  //   ],
  //   required: true,
  // },
  // {
  //   key: "socials",
  //   label: "where can we see your work?",
  //   type: "text", // TODO: should be social
  //   required: true,
  // },
  // {
  //   key: "additional_info",
  //   label: "is there anything else we should know?",
  //   type: "text",
  //   required: false,
  // },
];
